(in-package :cl-utils)

(defun SHOW-all-cl-utils ()
  (SHOW-all-arrays-and-vectors)
  (SHOW-all-association-lists)
  (SHOW-all-bit-vectors)
  (SHOW-all-booleans)
  (SHOW-all-compare-durations)
  (SHOW-all-dates-and-times)
  (SHOW-all-debug)
  (SHOW-all-equality)
  (SHOW-ffi-with-cffi)
  (SHOW-ffi-with-sb-alien)
  (SHOW-all-files)
  (SHOW-all-format)
  (SHOW-all-functions)
  (SHOW-all-hash-tables)
  (SHOW-all-high-order-functions)
  (SHOW-all-lazy)
  (SHOW-all-lists)
  (SHOW-all-macros)
  ;; (SHOW-all-mail-via-gmail) ; requires Internet connection
  (SHOW-all-math-functions)
  (SHOW-all-memoization)
  (SHOW-all-measure-duration)
  (SHOW-all-numbers-doubles)
  (SHOW-all-numbers-integers-french)
  (SHOW-all-numbers-integers)
  (SHOW-all-numbers-integers-primes)
  (SHOW-all-numbers-rationals)
  (SHOW-all-continued-fractions)
  (SHOW-all-farey-sequences)
  (SHOW-all-sorting)
  (SHOW-all-permutations)
  (SHOW-all-combinations)
  (SHOW-all-search)
  ;; (SHOW-all-gnuplot) ; requires Gnuplot installation
  (SHOW-all-console-charts)
  ;; (SHOW-all-os-interaction-windows) ; Windows-specific
  ;; (SHOW-all-ollama)
  (SHOW-all-optimization 4 5)
  ;; parallelism:
  ;;    (void)
  (SHOW-all-property-lists)
  (SHOW-all-sexp)
  (SHOW-all-strings)
  (SHOW-all-symbols)
  (SHOW-all-tco)
  (SHOW-all-trampoline)
  (SHOW-all-types)
  (SHOW-all-triangles)
  (SHOW-all-variables)
  ;; (SHOW-all-web) ; requires Internet connection
  nil
  )

(defun main ()
  (SHOW-all-cl-utils)
  (format t "~%Done.~%~%"))

;;; end
